# generated by datamodel-codegen:
#   filename:  metadata.json
#   timestamp: 2022-03-19T01:16:05+00:00

from __future__ import annotations

from .base import BaseModel


class BackupObjectInfo(BaseModel):
    compression: str
    length: int
    md5: str
    offset: int


class BackupMetadata(BaseModel):
    backup_description: str | None
    backup_id: str | None
    backup_name: str | None
    created_at: str | None
    objects: list[dict[str, BackupObjectInfo]]
    parent_id: str | None
    version: str | None
    volume_id: str | None
    volume_meta: str | None
